name: API and Lint Tests

on:
  push:
    branches:
      - main

jobs:
  run-lint-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: |
          cd frontend
          npm install
          cd server
          npm install
      - name: frontend lint test
        run: |
          cd frontend
          npm run lint
      - name: backend lint test
        run: |
          cd web
          npm run lint

  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: |
          cd frontend
          npm install
          cd server
          npm install
          npm install -g newman
      - name: run the server
        run: |
          cd server
          npm start &
      - name: api tests
        run: |
          newman run ./tests/scholarly.postman_collection.json
