name: API and Lint Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run-lint-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: |
          cd frontend
          npm install
          cd ../server
          npm install
      - name: frontend lint test
        run: |
          cd frontend
          npm run lint
      - name: backend lint test
        run: |
          cd server
          npm run lint

  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: |
          cd frontend
          npm install
          cd ../server
          npm install
          npm install -g newman
      - name: run the server
        run: |
          cd server
          npm start &
        env:
          DATABASE_CLIENT_URL: ${{ secrets.DATABASE_CLIENT_URL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          BBB_URL: ${{ secrets.BBB_URL }}
          BBB_SECRET: ${{ secrets.BBB_SECRET }}
      - name: api tests
        run: |
          newman run ./tests/scholarly.postman_collection.json
  
  push-to-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Push
        run: |
          git checkout -b deploy
          git push origin deploy -f