name: ESlint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: npm install
      - name: frontend lint test
        run: |
          cd frontend
          npm run lint
      - name: backend lint test
        run: |
          cd web
          npm run lint
